### ISSUE TITLE
sc-driver-tests needs to use cmake version <= 3.3.1

### ISSUE THREAD

**Issue by e-harvey** [ehein6/emu-microbench#3]

**Comment by e-harvey** [comment]
@ehein6: will emu-microbench build with CMake version 3.3.1?

**Comment by ehein6** [comment]
I believe it will, we can knock down the `cmake_minimum_required` if necessary. I don't have that version on hand to test with.

**Comment by e-harvey** [comment]
> I believe it will, we can knock down the cmake_minimum_required if necessary. I don't have that version on hand to test with.

Please do so. I tested it with cmake v3.3.1 and it works.
